title: "TechTopic.org"
email: contact@techtopic.org
timezone: UTC-5
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 30
disqus: 'techtopic-org'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
author: "TechTopic.org Team"
formspree: "mqknkdjp"

kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-1B71GH7Z62

# Social
social:
  instagram: https://www.instagram.com/techtopic_org/
  tiktok: https://tiktok.com/@techtopic.org
  youtube: https://www.youtube.com/channel/UCPFELz5VkpUfW157Ckp76Ag

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-loading-lazy 
